-- Here it goes the specific colorscheme. It's best to change specific things about the scheme
require('after.rose-pine')
require('after.telescope')
require('after.treesitter')
require('after.which-key')
require('after.mason')
require('after.neodev')
require('after.cmp')
require('after.harpoon')
require('after.mini')
require('after.rust-tools')
require('after.scala')
require('after.git-worktree')
require('after.neogit')
